name = "QRWithoutQ"
uuid = "e22447fe-70af-4459-ad9f-6b372900e932"
authors = ["Filip Tronarp <filip.tronarp@matstat.lu.se> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
